name: Deploy

permissions:
    id-token: write
    contents: read

on:
    workflow_dispatch:
        inputs:
          auto-approve:
            type: boolean
            default: false
            description: Skip plan approval

env:
    TF_INPUT: 0
    TF_IN_AUTOMATION: 1

jobs:
    plan:
        name: Plan
        environment: main
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            sparse-checkout: |
                terraform
        - name: Setup terraform
          uses: hashicorp/setup-terraform@v3
          with:
            cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}
        - name: Setup kubelogin
          uses: azure/use-kubelogin@v1
          with:
            kubelogin-version: v0.0.34
        - name: Azure login
          uses: azure/login@v1
          with:
            client-id: ${{ vars.ARM_CLIENT_ID }}
            tenant-id: ${{ vars.ARM_TENANT_ID }}
            subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}
        - name: Init
          run: terraform init -no-color
          working-directory: terraform
        - name: Validate
          run: terraform validate -no-color
          working-directory: terraform
        - name: Plan
          id: plan
          run: terraform plan -no-color
          working-directory: terraform
        - name: Apply
          if: inputs.auto-approve
          run: terraform apply -no-color -auto-approve
          working-directory: terraform